#line 2 "dolce.lex.yy.cpp"

#line 4 "dolce.lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[264] =
    {   0,
        0,    0,   84,   83,   82,   81,   14,   83,   67,   83,
       83,   60,   61,   55,   53,   65,   54,   66,   56,   71,
       71,   71,   71,   64,   57,   52,   69,   50,   68,   70,
       62,   63,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   58,
       83,   59,   48,    0,   73,    0,   45,    0,    0,   71,
        1,    2,    0,   71,   71,    0,    0,   71,   51,   47,
       49,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       35,   70,   70,   70,   70,   11,   70,   70,   70,   70,

       70,   70,   70,   70,   70,   70,   70,   70,   46,   74,
       72,   71,    0,    0,   76,   76,   76,   41,   70,   70,
       10,   70,   37,   70,   70,   70,   70,   27,   70,   70,
       70,   70,   70,   42,   70,   70,   70,   70,   22,   70,
        4,   70,   70,   70,   18,   70,   70,   36,   70,   70,
       70,   15,   70,   70,   70,    0,   71,   75,    0,   70,
       70,   19,   20,   44,   70,   70,   27,   70,   39,   70,
       70,   70,   70,   70,   70,   28,   70,   70,   70,   70,
       70,   70,   70,    9,   43,   70,   25,   70,   24,    0,
        0,    0,    0,    0,    0,    0,   70,   12,   70,   38,

       70,   70,   70,    5,   70,   23,   32,   28,   70,   16,
       70,   26,   70,   70,   70,   17,   25,   34,   24,    0,
        0,    0,    0,    0,    0,    7,   70,   33,   70,   13,
       70,   40,   29,   26,   70,   30,   21,   78,   75,    0,
        6,   70,   70,   29,   31,   30,    0,   77,    8,    3,
        0,    0,    0,    0,    0,   79,   77,    0,    0,    0,
        0,   80,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   22,   23,   23,   23,   23,   24,   25,   26,
       27,   28,    1,   29,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       31,   32,   33,    1,   30,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   30,   50,   51,   52,   53,   54,   55,   56,
       57,   30,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    3,    3,    1,    4,    4,    4,
        4,    4,    4,    3,    1,    1,    1,    1,    1,    5,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[268] =
    {   0,
        0,    0,  528,  529,  529,  529,  500,   55,  529,  518,
      493,  529,  529,  529,  529,  529,   44,  529,   56,   56,
       70,   80,   63,  529,  529,  497,  496,  495,  529,    0,
      529,  529,   70,   66,   74,   15,   74,  471,  472,  472,
      484,   81,  467,   63,   80,   80,   74,   90,  478,  529,
      456,  529,  529,  104,  529,  511,  529,  504,  131,  123,
      529,  529,  129,  137,  147,  146,  154,  162,  529,  529,
      529,    0,  461,  475,  458,  472,  470,  467,  472,  141,
      448,  452,  464,  452,  463,  448,  447,  450,  449,  443,
      136,  444,  445,  446,  445,    0,  434,  439,  453,  438,

      441,  440,  451,  432,  445,  444,  443,  446,  529,  529,
      177,  185,  192,  170,  198,  204,  450,    0,  440,  439,
        0,  442,    0,  425,  429,  424,  425,  420,  432,  430,
      190,  421,  429,    0,  432,  412,  414,  413,    0,  410,
        0,  408,  408,  414,    0,  410,  415,    0,  418,  412,
      412,    0,  409,  402,  401,  216,  225,  426,  231,  400,
      398,    0,    0,    0,  402,  394,    0,  409,    0,  392,
      396,  390,  391,  388,  390,  387,  399,  385,  383,  393,
      385,  385,  384,    0,    0,  385,  378,  390,  376,  237,
      245,  251,  257,  262,  269,  402,  373,    0,  386,    0,

      371,  373,  350,    0,  334,    0,    0,    0,  310,    0,
      291,  241,  257,  225,  202,    0,    0,    0,    0,  276,
      281,  210,  211,  287,  293,    0,  146,    0,  131,    0,
      135,    0,  103,    0,  101,   86,    0,  298,  529,  304,
        0,   88,   81,    0,    0,    0,  313,   46,    0,    0,
      319,  327,  333,  338,  344,  350,  529,  365,  356,  373,
      379,  385,  529,  408,  413,  415,  418
    } ;

static yyconst flex_int16_t yy_def[268] =
    {   0,
      263,    1,  263,  263,  263,  263,  263,  264,  263,  263,
      265,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,   22,  263,  263,  263,  263,  263,  263,  266,
      263,  263,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  263,
      263,  263,  263,  264,  263,  264,  263,  263,  265,  263,
      263,  263,  263,  263,  267,  263,  263,  263,  263,  263,
      263,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  263,  263,  263,  263,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  263,
      263,  263,  263,  263,  263,  263,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  263,
      263,  263,  263,  263,  263,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  263,  263,  263,
      266,  266,  266,  266,  266,  266,  263,  263,  266,  266,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,    0,  263,  263,  263,  263
    } ;

static yyconst flex_uint16_t yy_nxt[590] =
    {   0,
        4,    5,    6,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   23,   23,   24,   25,   26,   27,   28,   29,   30,
       31,    4,   32,   33,   30,   34,   35,   36,   37,   38,
       39,   40,   30,   30,   41,   42,   30,   43,   44,   30,
       45,   46,   47,   30,   48,   30,   49,   50,   51,   52,
       55,   60,   60,   60,   60,   60,   60,   61,   85,  253,
       86,   63,   62,   64,   65,   65,   65,   65,   65,   66,
       68,   68,   68,   68,   67,   63,   56,   65,   65,   65,
       64,   64,   64,   66,   67,   63,   97,   64,   64,   64,

       64,   68,   68,   66,   73,   74,   79,   81,   75,   55,
       98,   82,   87,   80,   93,   83,   76,   99,   88,   77,
      104,  102,   94,   78,  105,  250,   84,  106,   95,  103,
      107,  100,  101,  263,  249,   56,  246,  245,   63,   58,
       60,   60,   60,   60,   60,   60,  111,  111,  111,  111,
      111,  111,   63,  244,  112,  112,  112,  112,  112,  112,
       66,   67,   63,  113,  113,  113,  113,  113,  243,  138,
       66,  114,  115,  115,  116,  117,  117,   63,  242,  112,
      112,  112,  112,  112,  112,  125,  126,  139,  117,  117,
      117,  117,  117,  127,  111,  111,  111,  111,  111,  111,

       63,  241,  157,  157,  157,  157,  157,  157,  156,  158,
      158,  158,  158,  158,  158,  117,  117,  117,  117,  117,
      117,  117,  117,  170,   67,   67,  159,  223,  223,  223,
      190,  171,  159,  191,  191,  191,  191,  191,  191,  192,
       63,  237,   60,   60,   60,   60,   60,   60,  194,  194,
      195,  196,  196,  196,  191,  191,  191,  191,  191,  191,
      220,  236,  191,  191,  191,  191,  191,  191,  221,  222,
      223,  223,  223,  223,  224,  224,  224,  224,  224,  196,
      196,  196,  196,  196,  196,  225,  196,  196,  196,  196,
      235,  234,  225,  238,  238,  238,  238,  238,  238,  223,

      223,  223,  223,  223,  239,  239,  239,  239,  239,  239,
      240,  240,  240,  240,  240,  238,  238,  238,  238,  238,
      238,  248,  248,  248,  248,  248,  248,  251,  233,  247,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  254,  232,  252,  252,  252,  252,  252,  252,
      255,  255,  255,  255,  255,  256,  256,  256,  256,  256,
      256,  257,  257,  257,  257,  257,  257,  256,  256,  256,
      256,  256,  256,  260,  260,  260,  260,  260,  260,  259,
      231,  258,  260,  260,  260,  260,  260,  260,  261,  230,
      260,  260,  260,  260,  260,  260,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,   54,   54,
       54,   54,   54,   58,  229,   58,   58,   58,   72,   72,
      112,  112,  228,  227,  226,  225,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  193,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  137,  136,  135,  134,  133,

      132,  131,  130,  129,  128,  124,  123,  122,  121,  120,
      119,  118,  110,  263,  109,  108,   96,   92,   91,   90,
       89,   71,   70,   69,   59,   57,   53,  263,    3,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263
    } ;

static yyconst flex_int16_t yy_chk[590] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,   17,   17,   17,   17,   17,   17,   19,   36,  248,
       36,   20,   19,   20,   20,   20,   20,   20,   20,   20,
       23,   23,   23,   23,   21,   21,    8,   21,   21,   21,
       21,   21,   21,   21,   22,   22,   44,   22,   22,   22,

       22,   22,   22,   22,   33,   33,   34,   35,   33,   54,
       44,   35,   37,   34,   42,   35,   33,   45,   37,   33,
       47,   46,   42,   33,   47,  243,   35,   48,   42,   46,
       48,   45,   45,   59,  242,   54,  236,  235,   60,   59,
       60,   60,   60,   60,   60,   60,   63,   63,   63,   63,
       63,   63,   64,  233,   64,   64,   64,   64,   64,   64,
       64,   65,   65,   66,   66,   66,   66,   66,  231,   91,
       65,   67,   67,   67,   67,   67,   67,   68,  229,   68,
       68,   68,   68,   68,   68,   80,   80,   91,  114,  114,
      114,  114,  114,   80,  111,  111,  111,  111,  111,  111,

      112,  227,  112,  112,  112,  112,  112,  112,  111,  113,
      113,  113,  113,  113,  113,  115,  115,  115,  115,  115,
      115,  116,  116,  131,  222,  223,  115,  222,  222,  222,
      156,  131,  116,  156,  156,  156,  156,  156,  156,  157,
      157,  215,  157,  157,  157,  157,  157,  157,  159,  159,
      159,  159,  159,  159,  190,  190,  190,  190,  190,  190,
      191,  214,  191,  191,  191,  191,  191,  191,  192,  192,
      192,  192,  192,  192,  193,  193,  193,  193,  193,  194,
      194,  194,  194,  194,  194,  194,  195,  195,  195,  195,
      213,  212,  195,  220,  220,  220,  220,  220,  220,  221,

      221,  221,  221,  221,  224,  224,  224,  224,  224,  224,
      225,  225,  225,  225,  225,  238,  238,  238,  238,  238,
      238,  240,  240,  240,  240,  240,  240,  247,  211,  238,
      247,  247,  247,  247,  247,  247,  251,  251,  251,  251,
      251,  251,  252,  209,  252,  252,  252,  252,  252,  252,
      253,  253,  253,  253,  253,  254,  254,  254,  254,  254,
      254,  255,  255,  255,  255,  255,  255,  256,  256,  256,
      256,  256,  256,  259,  259,  259,  259,  259,  259,  258,
      205,  256,  258,  258,  258,  258,  258,  258,  260,  203,
      260,  260,  260,  260,  260,  260,  261,  261,  261,  261,

      261,  261,  262,  262,  262,  262,  262,  262,  264,  264,
      264,  264,  264,  265,  202,  265,  265,  265,  266,  266,
      267,  267,  201,  199,  197,  196,  189,  188,  187,  186,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  168,  166,  165,  161,  160,  158,
      155,  154,  153,  151,  150,  149,  147,  146,  144,  143,
      142,  140,  138,  137,  136,  135,  133,  132,  130,  129,
      128,  127,  126,  125,  124,  122,  120,  119,  117,  108,
      107,  106,  105,  104,  103,  102,  101,  100,   99,   98,
       97,   95,   94,   93,   92,   90,   89,   88,   87,   86,

       85,   84,   83,   82,   81,   79,   78,   77,   76,   75,
       74,   73,   58,   56,   51,   49,   43,   41,   40,   39,
       38,   28,   27,   26,   11,   10,    7,    3,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "dolce.l"
/**
  Copyright (C) 2016 ATOS
 
    This file is part of BCEP.

    BCEP is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BCEP is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BCEP.  If not, see <http://www.gnu.org/licenses/>.
 
  Authors:
  ATOS ARI
  
 */
/*
	Dolce - DescriptOn Language for Complex Events.
	Lexical Tokens for Grammar Specification-1
	

	TODO: Reconsider the {YY}, {MM} etc. tokens and either
		- raise specialized syntax err in parseTime()
		- consider any out-of-range time values as semantic errors (not lexing errors)
		
	TODO: Same as the above, but for geographic constants.
		
*/
#line 56 "dolce.l"

#include "ParserContext.h"

#include <stdio.h>
#include "../DolceCompilerCodes.h"
#include "../../Types/TPosLiteral.h"
#include "../../Types/TAreaLiteral.h"
#include "../../Types/TTimeLiteral.h"
#include "../../Types/TDurationLiteral.h"
#include "Parser.h"
#include "ASTree.h"
#include "ErrorList.h"


#include "dolce.y.tab.hpp"

void count(yyscan_t yyscanner);
void countline(yyscan_t yyscanner);
void eat_star_comments(yyscan_t yyscanner);
void eat_line_comments(yyscan_t yyscanner);
TPosLiteral parsePos(yyscan_t yyscanner);
TAreaLiteral parseArea(yyscan_t yyscanner, const int _mode);
void parseGeographicLiterals(yyscan_t yyscanner, float* _list_, const int _count);
TTimeLiteral parseTime(yyscan_t yyscanner, const int _mode);
char parseChar(yyscan_t yyscanner);
char* parseString(yyscan_t yyscanner);
void countNewLine(yyscan_t yyscanner, char c);
TDurationLiteral parseDuration(const int _count, const TDurationUnit _unit);
TDurationLiteral durationUnitAsSeconds(const TDurationUnit _unit);

/* FUTURE
"ms"				{ return MILLISEC; }
"us"				{ return MICROSEC; }
"ns"				{ return NANOSEC; }
"delegate"			{ return DELEGATE; }
*/

#line 732 "dolce.lex.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */

#ifndef _WIN32
#include <unistd.h>
#else
#include <io.h>
#endif

#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * _in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * _out_str ,yyscan_t yyscanner );

yy_size_t yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int _line_number ,yyscan_t yyscanner );

int yyget_column  (yyscan_t yyscanner );

void yyset_column (int _column_no ,yyscan_t yyscanner );

YYSTYPE * yyget_lval (yyscan_t yyscanner );

void yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *yyget_lloc (yyscan_t yyscanner );
    
        void yyset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	{
#line 96 "dolce.l"

#line 1019 "dolce.lex.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 264 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 529 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 97 "dolce.l"
{ eat_star_comments(yyscanner); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 98 "dolce.l"
{ eat_line_comments(yyscanner); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 102 "dolce.l"
{ return EXTERNAL; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 103 "dolce.l"
{ return MAP; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 104 "dolce.l"
{ return EVENT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 105 "dolce.l"
{ return COMPLEX_EVENT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 106 "dolce.l"
{ return ACCEPT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 107 "dolce.l"
{ return DURATION; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 108 "dolce.l"
{ return TIME; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 110 "dolce.l"
{ return AND_EOP; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 111 "dolce.l"
{ return OR_EOP; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 112 "dolce.l"
{ return AFTER_EOP; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 113 "dolce.l"
{ return DURING_EOP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 114 "dolce.l"
{ return ABSENCE_UNARY_EOP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 116 "dolce.l"
{ return USE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 117 "dolce.l"
{ return LASTS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 118 "dolce.l"
{ return UNTIL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 120 "dolce.l"
{ return POS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 121 "dolce.l"
{ return AREA; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 122 "dolce.l"
{ return CHAR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 123 "dolce.l"
{ return STRING; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 124 "dolce.l"
{ return INT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 125 "dolce.l"
{ return FLOAT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 126 "dolce.l"
{ return YEARS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 127 "dolce.l"
{ return WEEKS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 128 "dolce.l"
{ return MONTHS; } 
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 129 "dolce.l"
{ return DAYS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 130 "dolce.l"
{ return HOURS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 131 "dolce.l"
{ return MINUTES; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 132 "dolce.l"
{ return SECONDS; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 135 "dolce.l"
{ return PAYLOAD; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 136 "dolce.l"
{ return GROUP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 137 "dolce.l"
{ return DETECT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 138 "dolce.l"
{ return WHERE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 139 "dolce.l"
{ return IN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 141 "dolce.l"
{ return SUM_FUNC; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 142 "dolce.l"
{ return AVG_FUNC; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 143 "dolce.l"
{ return COUNT_FUNC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 144 "dolce.l"
{ return DIFF_FUNC; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 145 "dolce.l"
{ return INAREA_FUNC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 146 "dolce.l"
{ return ABS_FUNC; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 147 "dolce.l"
{ return FFT_FUNC; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 148 "dolce.l"
{ return TRAJ_FUNC; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 149 "dolce.l"
{ return COLL_FUNC; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 151 "dolce.l"
{ return AND_OP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 152 "dolce.l"
{ return OR_OP; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 154 "dolce.l"
{ return EQ_OP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 155 "dolce.l"
{ return NE_OP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 156 "dolce.l"
{ return GE_OP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 157 "dolce.l"
{ return GT_OP; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 158 "dolce.l"
{ return LE_OP; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 159 "dolce.l"
{ return LT_OP; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 161 "dolce.l"
{ return ADD_OP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 162 "dolce.l"
{ return SUB_OP; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 163 "dolce.l"
{ return MULT_OP; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 164 "dolce.l"
{ return DIV_OP; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 166 "dolce.l"
{ return (';'); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 167 "dolce.l"
{ return ('{'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 168 "dolce.l"
{ return ('}'); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 169 "dolce.l"
{ return ('('); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 170 "dolce.l"
{ return (')'); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 171 "dolce.l"
{ return ('['); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 172 "dolce.l"
{ return (']'); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 173 "dolce.l"
{ return (':'); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 174 "dolce.l"
{ return (','); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 175 "dolce.l"
{ return ('.'); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 176 "dolce.l"
{ return ('$'); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 177 "dolce.l"
{ return ('@'); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 178 "dolce.l"
{ return ('='); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 180 "dolce.l"
{ yylval->a_string = yytext; 
						return IDENTIFIER;
					}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 183 "dolce.l"
{ yylval->a_duration_unit = (TDurationUnit)atoi(yytext);
						return INTEGER_CONSTANT;
					}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 187 "dolce.l"
{ yylval->a_float = atof(yytext);
						return FLOAT_CONSTANT;
					}			
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 191 "dolce.l"
{	yylval->a_string = parseString(yyscanner); 
						return STRING_LITERAL;
					}		
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 195 "dolce.l"
{	yylval->a_char = parseChar(yyscanner);
						return CHARACTER_CONSTANT;
					}		
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 199 "dolce.l"
{ 
						yylval->a_time = parseTime(yyscanner, 0);
						return TIME_CONSTANT;
					}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 204 "dolce.l"
{ 
						yylval->a_time = parseTime(yyscanner, 1);
						return TIME_CONSTANT;
					}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 209 "dolce.l"
{ 
						yylval->a_time = parseTime(yyscanner, 2);
						return TIME_CONSTANT;
					}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 214 "dolce.l"
{ 	yylval->a_pos = parsePos(yyscanner);
						return POS_CONSTANT;
					}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 218 "dolce.l"
{ yylval->a_area = parseArea(yyscanner, 0);
						return AREA_CONSTANT;
					}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 222 "dolce.l"
{ yylval->a_area = parseArea(yyscanner, 1);
						return AREA_CONSTANT;
					}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 227 "dolce.l"
{ countline(yyscanner);  }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 228 "dolce.l"
;	/* ignore whitespace */
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 231 "dolce.l"
ECHO;
	YY_BREAK
#line 1519 "dolce.lex.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	yy_size_t number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 264 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 264 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 263);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

#ifndef _WIN32
    b->yy_is_interactive = file ? (isatty(fileno(file)) > 0) : 0;
#else
    b->yy_is_interactive = file ? (_isatty( _fileno(file) ) > 0) : 0;
#endif

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 231 "dolce.l"




void yyerror(YYLTYPE* loc, ParserContext* _context, const char* _msg)
{
	_context->parser->mErrorList->addError(
								loc->first_line,
								loc->first_column,
								"%d: '%s'",
								DMSG_SYNTAX_ERROR,
								_msg);
	
}



void count(yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	YYLTYPE* loc = yyget_lloc(yyscanner);
	
	int i;
	char c;

	
	for (i = 0; (c = yytext[i]) != '\0'; i++)
	{
		if((c == '\n') || (c == '\r'))
		{
			// Make sure we do not recount when CR-LF
			if(c == '\r')
			{
				i++;
				if((c != '\n') && (c != '\0'))
					i--;
			}
			
			loc->first_line++;
			loc->first_column = 0;
		}
		else if (yytext[i] == '\t')
			loc->first_column += 8 - (loc->first_column % 8);
		else
			loc->first_column++;
	}
}

void countline(yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	char c = yytext[0];
	
	countNewLine(yyscanner, c);
}


TPosLiteral parsePos(yyscan_t yyscanner)
{
	float list[2];
	
	parseGeographicLiterals(yyscanner, list,  2);

	TPosLiteral ret;
	
	ret.lat = list[0];
	ret.lon = list[1];

#ifdef CEP_DEBUG
	printf("lat=%f,lon=%f\n", list[0], list[1]); fflush(stdout);
#endif

	return ret;
}



/* mode: 0-circular, 1-rectangular */
TAreaLiteral parseArea(yyscan_t yyscanner, const int _mode)
{
	float list[4];
	
	int max = (_mode == TAreaLiteral::KAreaCircular) ? 3 : 4;
	
	parseGeographicLiterals(yyscanner, list,  max);

	TAreaLiteral ret;
	
	ret.type = _mode;
	ret.lat = list[0];
	ret.lon = list[1];
	ret.lat2 = list[2];
	
	if(_mode == TAreaLiteral::KAreaCircular)
		ret.radius = list[2];
	else
		ret.lon2 = list[3];

#ifdef CEP_DEBUG		
	if(_mode == TAreaLiteral::KAreaCircular)
		printf("lat=%f,lon=%f,radius=%f\n", list[0], list[1], list[2]); fflush(stdout);
	if(_mode == TAreaLiteral::KAreaRectangular)
		printf("lat=%f,lon=%f,lat=%f,lon=%f\n", list[0], list[1], list[2], list[3]); fflush(stdout);
#endif
	
	return ret;
}


	
void parseGeographicLiterals(yyscan_t yyscanner, float* _list_, const int _count)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/*  
		So yes, we're manually lexing within the lexer, but we REALLY want
		these as built-in types, i.e. as literals, not a composition of tokens to 
		parsed upstream as single grammar elements - ML
	*/
	char* tok = (char*)malloc(strlen(yytext) + 1);  /* avoid buffer overflow (security) */
	char* tokBegin = tok;
	char c;
	
	int idx = 0;

	while((c = *yytext) != '\0')
	{
		if((c == '\\') || (c == '\0'))
		{
			*tok = '\0';
			tok = tokBegin;
			if(idx < _count)
				_list_[idx++] = atof(tok);
				
			yytext++;
		}
		else
		{
			*tok++ = *yytext++;
			*tok = 0;
		}
	}
	*tok = '\0';
	tok = tokBegin;
	
	if(idx < _count)
		_list_[idx++] = atof(tokBegin);
		
	free(tok);
}


/* _mode: 0-only time, 1-date+time */
TTimeLiteral parseTime(yyscan_t yyscanner, const int _mode)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	#ifdef CEP_DEBUG
	printf("\nZTIME DETECTED (%d)\n", _mode); 
#endif
	char* tok = (char*)malloc(strlen(yytext) + 1);  /* avoid buffer overflow */
	char* tokBegin = tok;
	char c;
	
	int idx = 0;
	int _count = 3;
	char val[3] = { 0,0,0 };

	while((c = *yytext) != '\0')
	{
		if((c == ':') || (c == '\0'))
		{
			*tok = '\0';
			tok = tokBegin;
			if(idx < _count)
				val[idx++] = atoi(tok);
				
			yytext++;
		}
		else
		{
			*tok++ = *yytext++;
			*tok = 0;
		}
	}
	*tok = '\0';
	tok = tokBegin;
	
	if(idx < _count)
		val[idx++] = atoi(tok);
		
	free(tok);
	
	TTimeLiteral tm;
	tm.time.tm_hour=val[0];
	tm.time.tm_min=val[1];
	tm.time.tm_sec=val[2];
	
#ifdef CEP_DEBUG
	printf("\n****** TIME = %d:%d:%d\n", tm.time.tm_hour, tm.time.tm_min, tm.time.tm_sec);
#endif

	return tm;
}



void eat_star_comments(yyscan_t yyscanner)
{
/*


<*>.|\n     		{ fprintf(stderr, "Unrecognized symbol '%s'\n", yytext); }
*/
	char c, tmp;
loop:
	while ((c = yyinput(yyscanner)) != '*' && c != 0)
	{
		countNewLine(yyscanner, c);
	}

	if ((tmp = yyinput(yyscanner)) != '/' && c != 0)
	{
		goto loop;
	}
}

void eat_line_comments(yyscan_t yyscanner)
{

	char c;

	while (((c = yyinput(yyscanner)) != '\n') && (c != '\r')  && (c != 0))
		;
		
	countNewLine(yyscanner, c);
}


void countNewLine(yyscan_t yyscanner, char c)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	YYLTYPE* loc = yyget_lloc(yyscanner);

	if((c=='\n') || (c=='\r'))
	{
		// make sure we do not double-count in case of CR-LF files
		if(c=='\r')
		{
			/* eat the LF if necessary */
			c = yyinput(yyscanner);
			if((c != '\n') && (c != '\0'))
				unput(c);
		}
		loc->first_line++;
	}
	
}


char parseChar(yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	int l = strlen(yytext);

	if(l == 3)
		return yytext[1];
		
	if(l == 4)
		return(yytext[2]);
	
	return 0;
}


char* parseString(yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* copy yytext, then manipulate yytext directly.  */
	char* orig = (char*)malloc(strlen(yytext) + 1);
	
	strcpy(orig, yytext+1);

	char* yytextBegin = yytext;
	char* origBegin = orig;
	
	while((*orig != '"') && (*orig != '\0'))
	{
		if(*orig == '\\')
			orig++;
		*yytext++ = *orig++;
	}
	*yytext = '\0';
	
	free(origBegin);
	
	return yytextBegin;
}


